name: Coch Design
favicon: null
layout_spectrum: 0.49335
typography_spectrum: 0.56258
title: Coch Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262523'
    - '#767676'
    - '#9f9f9f'
    - '#d6d6d6'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
