title: Coch Design
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.1827957
  brandColors:
    - '#ffffff'
    - '#262523'
    - '#767676'
    - '#9f9f9f'
    - '#d6d6d6'
  rhythmicContrast: 0.7043011
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Coch Design
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3243728
layout_spectrum: 0.265233
