name: Coch Design
favicon: null
layout_spectrum: 0.31656092614866793
typography_spectrum: 0.56258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23269906220957637
  lightness: 0.2306455411016941
  saturation: 0.4874213037546724
  rhythmicContrast: 0.5346258126664907
purpose: []
